spring:
  datasource:
    username: root
    password: 20021012
    url: jdbc:mysql://localhost:3306/peer_learning_system
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #redis服务器地址
    host: 127.0.0.1
#    host: redis
#    host: 43.143.130.130 #服务器地址
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 0
        #连接超时时间（毫秒）
    timeout: 30000

mail:
  host: smtp.qq.com
  username: 1832271620@qq.com
  password: cahoceiyhgpfejbc
